### ISSUE TITLE
missing models

### ISSUE THREAD

**Issue by bruhlikewhat** [g0kuvonlange/vrswap#3]
(vrswap) C:\Users\--------\Downloads\vrswap-main>python vr-splitter.py --frames_folder C:\Users\--------\Downloads\vrswap-main\TEST\Processing --gpu --gpu_threads 8
ERROR:root:File "w600k_r50.onnx" does not exist!

where is this supposed to go?

**Comment by g0kuvonlange** [comment]
In the root folder, still needs to be optimised to retrieve the global installed Insightface folder. 

Just add the model to the root folder for now and it should work.
